/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _FineRTD_H_
#define _FineRTD_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* FineRTD */
    typedef long FineRTD_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_FineRTD;
    asn_struct_free_f FineRTD_free;
    asn_struct_print_f FineRTD_print;
    asn_constr_check_f FineRTD_constraint;
    ber_type_decoder_f FineRTD_decode_ber;
    der_type_encoder_f FineRTD_encode_der;
    xer_type_decoder_f FineRTD_decode_xer;
    xer_type_encoder_f FineRTD_encode_xer;
    per_type_decoder_f FineRTD_decode_uper;
    per_type_encoder_f FineRTD_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _FineRTD_H_ */
#include <asn_internal.h>
