/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _GANSSDiffCorrections_H_
#define _GANSSDiffCorrections_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "SeqOfSgnTypeElement.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* GANSSDiffCorrections */
    typedef struct GANSSDiffCorrections
    {
        long dganssRefTime;
        SeqOfSgnTypeElement_t sgnTypeList;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } GANSSDiffCorrections_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_GANSSDiffCorrections;

#ifdef __cplusplus
}
#endif

#endif /* _GANSSDiffCorrections_H_ */
#include <asn_internal.h>
