/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _GANSSRefMeasurementElement_H_
#define _GANSSRefMeasurementElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SVID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* Forward declarations */
    struct AdditionalDopplerFields;
    struct AddionalAngleFields;

    /* GANSSRefMeasurementElement */
    typedef struct GANSSRefMeasurementElement
    {
        SVID_t svID;
        long doppler0;
        struct AdditionalDopplerFields *additionalDoppler /* OPTIONAL */;
        long codePhase;
        long intCodePhase;
        long codePhaseSearchWindow;
        struct AddionalAngleFields *additionalAngle /* OPTIONAL */;
        /*
	 * This type is extensible,
	 * possible extensions are below.
	 */

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } GANSSRefMeasurementElement_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_GANSSRefMeasurementElement;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AdditionalDopplerFields.h"
#include "AddionalAngleFields.h"

#endif /* _GANSSRefMeasurementElement_H_ */
#include <asn_internal.h>
