/*
 * SPDX-FileCopyrightText: (c) 2003, 2004 Lev Walkin <vlm@lionet.info>. All rights reserved.
 * SPDX-License-Identifier: BSD-1-Clause
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 *     found in "../rrlp-components.asn"
 */

#include "GSMTime.h"

static asn_TYPE_member_t asn_MBR_GSMTime_1[] = {
    {ATF_NOFLAGS, 0, offsetof(struct GSMTime, bcchCarrier),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_BCCHCarrier,
        0, /* Defer constraints checking to the member type */
        0, /* No PER visible constraints */
        0, "bcchCarrier"},
    {ATF_NOFLAGS, 0, offsetof(struct GSMTime, bsic),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_BSIC, 0,                       /* Defer constraints checking to the member type */
        0,                                      /* No PER visible constraints */
        0, "bsic"},
    {ATF_NOFLAGS, 0, offsetof(struct GSMTime, frameNumber),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_FrameNumber,
        0, /* Defer constraints checking to the member type */
        0, /* No PER visible constraints */
        0, "frameNumber"},
    {ATF_NOFLAGS, 0, offsetof(struct GSMTime, timeSlot),
        (ASN_TAG_CLASS_CONTEXT | (3 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_TimeSlot, 0,                   /* Defer constraints checking to the member type */
        0,                                      /* No PER visible constraints */
        0, "timeSlot"},
    {ATF_NOFLAGS, 0, offsetof(struct GSMTime, bitNumber),
        (ASN_TAG_CLASS_CONTEXT | (4 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_BitNumber, 0,                  /* Defer constraints checking to the member type */
        0,                                      /* No PER visible constraints */
        0, "bitNumber"},
};
static ber_tlv_tag_t asn_DEF_GSMTime_tags_1[] = {
    (ASN_TAG_CLASS_UNIVERSAL | (16 << 2))};
static asn_TYPE_tag2member_t asn_MAP_GSMTime_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* bcchCarrier at 630 */
    {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* bsic at 631 */
    {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0}, /* frameNumber at 632 */
    {(ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0}, /* timeSlot at 633 */
    {(ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0}  /* bitNumber at 635 */
};
static asn_SEQUENCE_specifics_t asn_SPC_GSMTime_specs_1 = {
    sizeof(struct GSMTime),
    offsetof(struct GSMTime, _asn_ctx),
    asn_MAP_GSMTime_tag2el_1,
    5, /* Count of tags in the map */
    0,
    0,
    0,  /* Optional elements (not needed) */
    -1, /* Start extensions */
    -1  /* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_GSMTime = {
    "GSMTime",
    "GSMTime",
    SEQUENCE_free,
    SEQUENCE_print,
    SEQUENCE_constraint,
    SEQUENCE_decode_ber,
    SEQUENCE_encode_der,
    SEQUENCE_decode_xer,
    SEQUENCE_encode_xer,
    SEQUENCE_decode_uper,
    SEQUENCE_encode_uper,
    0, /* Use generic outmost tag fetcher */
    asn_DEF_GSMTime_tags_1,
    sizeof(asn_DEF_GSMTime_tags_1) / sizeof(asn_DEF_GSMTime_tags_1[0]), /* 1 */
    asn_DEF_GSMTime_tags_1,                                             /* Same as above */
    sizeof(asn_DEF_GSMTime_tags_1) / sizeof(asn_DEF_GSMTime_tags_1[0]), /* 1 */
    0,                                                                  /* No PER visible constraints */
    asn_MBR_GSMTime_1,
    5,                       /* Elements count */
    &asn_SPC_GSMTime_specs_1 /* Additional specs */
};
