/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _ModuloTimeSlot_H_
#define _ModuloTimeSlot_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ModuloTimeSlot */
typedef long ModuloTimeSlot_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ModuloTimeSlot;
asn_struct_free_f ModuloTimeSlot_free;
asn_struct_print_f ModuloTimeSlot_print;
asn_constr_check_f ModuloTimeSlot_constraint;
ber_type_decoder_f ModuloTimeSlot_decode_ber;
der_type_encoder_f ModuloTimeSlot_encode_der;
xer_type_decoder_f ModuloTimeSlot_decode_xer;
xer_type_encoder_f ModuloTimeSlot_encode_xer;
per_type_decoder_f ModuloTimeSlot_decode_uper;
per_type_encoder_f ModuloTimeSlot_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _ModuloTimeSlot_H_ */
#include <asn_internal.h>
