/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _RequestIndex_H_
#define _RequestIndex_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* RequestIndex */
    typedef long RequestIndex_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_RequestIndex;
    asn_struct_free_f RequestIndex_free;
    asn_struct_print_f RequestIndex_print;
    asn_constr_check_f RequestIndex_constraint;
    ber_type_decoder_f RequestIndex_decode_ber;
    der_type_encoder_f RequestIndex_encode_der;
    xer_type_decoder_f RequestIndex_decode_xer;
    xer_type_encoder_f RequestIndex_encode_xer;
    per_type_decoder_f RequestIndex_decode_uper;
    per_type_encoder_f RequestIndex_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _RequestIndex_H_ */
#include <asn_internal.h>
