/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _SatelliteID_H_
#define _SatelliteID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SatelliteID */
typedef long SatelliteID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SatelliteID;
asn_struct_free_f SatelliteID_free;
asn_struct_print_f SatelliteID_print;
asn_constr_check_f SatelliteID_constraint;
ber_type_decoder_f SatelliteID_decode_ber;
der_type_encoder_f SatelliteID_encode_der;
xer_type_decoder_f SatelliteID_decode_xer;
xer_type_encoder_f SatelliteID_encode_xer;
per_type_decoder_f SatelliteID_decode_uper;
per_type_encoder_f SatelliteID_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _SatelliteID_H_ */
#include <asn_internal.h>
