/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../rrlp-components.asn"
 */

#ifndef _TA0_H_
#define _TA0_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TA0 */
typedef long TA0_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TA0;
asn_struct_free_f TA0_free;
asn_struct_print_f TA0_print;
asn_constr_check_f TA0_constraint;
ber_type_decoder_f TA0_decode_ber;
der_type_encoder_f TA0_encode_der;
xer_type_decoder_f TA0_decode_xer;
xer_type_encoder_f TA0_encode_xer;
per_type_decoder_f TA0_decode_uper;
per_type_encoder_f TA0_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _TA0_H_ */
#include <asn_internal.h>
