<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GpsCnavEphemerisType">
    <xs:complexContent>
      <xs:extension base="GnssEphemerisType">
        <xs:sequence>
          <xs:element name="toe1" type="xs:int"/>
          <xs:element name="toe2" type="xs:int"/>
          <!-- CEI/URA fields were added in archive version 1. -->
          <xs:sequence minOccurs="0">
            <xs:element name="WNop" type="xs:int"/>
            <xs:element name="top" type="xs:int"/>
            <xs:element name="URAED" type="xs:int"/>
            <xs:element name="URANED0" type="xs:int"/>
            <xs:element name="URANED1" type="xs:int"/>
            <xs:element name="URANED2" type="xs:int"/>
            <xs:element name="URA" type="xs:int"/>
            <xs:element name="URA0" type="xs:double"/>
            <xs:element name="URA1" type="xs:double"/>
            <xs:element name="URA2" type="xs:double"/>
          </xs:sequence>
          <!-- Added in archive version 2. -->
          <xs:element name="delta_ndot" type="xs:double" minOccurs="0"/>
          <xs:element name="TGD" type="xs:double"/>
          <xs:element name="ISCL1" type="xs:double"/>
          <xs:element name="ISCL2" type="xs:double"/>
          <xs:element name="ISCL5I" type="xs:double"/>
          <xs:element name="ISCL5Q" type="xs:double"/>
          <xs:element name="delta_A" type="xs:double"/>
          <xs:element name="Adot" type="xs:double"/>
          <xs:element name="delta_OMEGAdot" type="xs:double"/>
          <xs:element name="integrity_status_flag" type="xs:boolean"/>
          <xs:element name="l2c_phasing_flag" type="xs:boolean"/>
          <xs:element name="alert_flag" type="xs:boolean"/>
          <xs:element name="antispoofing_flag" type="xs:boolean"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GpsCnavEphemerisMapItemType">
    <xs:sequence>
      <xs:element name="first" type="xs:int"/>
      <xs:element name="second" type="GpsCnavEphemerisType"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:complexType name="GpsCnavEphemerisMapType">
    <xs:sequence>
      <xs:element name="count" type="xs:nonNegativeInteger"/>
      <xs:element name="item_version" type="xs:nonNegativeInteger"/>
      <xs:element name="item" type="GpsCnavEphemerisMapItemType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_cnav_ephemeris_map" type="GpsCnavEphemerisMapType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
