<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GpsEphemerisType">
    <xs:complexContent>
      <xs:extension base="GnssEphemerisType">
        <xs:sequence>
          <xs:element name="IODE_SF2" type="xs:int"/>
          <xs:element name="IODE_SF3" type="xs:int"/>
          <xs:element name="code_on_L2" type="xs:int"/>
          <xs:element name="L2_P_data_flag" type="xs:boolean"/>
          <xs:element name="SV_accuracy" type="xs:int"/>
          <xs:element name="SV_health" type="xs:int"/>
          <xs:element name="TGD" type="xs:double"/>
          <xs:element name="IODC" type="xs:int"/>
          <xs:element name="AODO" type="xs:int"/>
          <xs:element name="fit_interval_flag" type="xs:boolean"/>
          <xs:element name="spare1" type="xs:double"/>
          <xs:element name="spare2" type="xs:double"/>
          <xs:element name="integrity_status_flag" type="xs:boolean"/>
          <xs:element name="alert_flag" type="xs:boolean"/>
          <xs:element name="antispoofing_flag" type="xs:boolean"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GpsEphemerisMapItemType">
    <xs:sequence>
      <xs:element name="first" type="xs:int"/>
      <xs:element name="second" type="GpsEphemerisType"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:complexType name="GpsEphemerisMapType">
    <xs:sequence>
      <xs:element name="count" type="xs:nonNegativeInteger"/>
      <xs:element name="item_version" type="xs:nonNegativeInteger"/>
      <xs:element name="item" type="GpsEphemerisMapItemType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_ephemeris_map" type="GpsEphemerisMapType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
