<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GalileoEphemerisType">
    <xs:complexContent>
      <xs:extension base="GnssEphemerisType">
        <xs:sequence>
          <xs:element name="IOD_ephemeris" type="xs:int"/>
          <xs:element name="IOD_nav" type="xs:int"/>
          <xs:element name="SISA" type="xs:int"/>
          <xs:element name="E5a_HS" type="xs:int"/>
          <xs:element name="E5b_HS" type="xs:int"/>
          <xs:element name="E1B_HS" type="xs:int"/>
          <xs:element name="E5a_DVS" type="xs:boolean"/>
          <xs:element name="E5b_DVS" type="xs:boolean"/>
          <xs:element name="E1B_DVS" type="xs:boolean"/>
          <xs:element name="BGD_E1E5a" type="xs:double"/>
          <xs:element name="BGD_E1E5b" type="xs:double"/>
          <xs:element name="flag_all_ephemeris" type="xs:boolean"/>
          <xs:element name="nav_message_type" type="xs:unsignedInt" minOccurs="0"/>
          <xs:element name="nav_message_source" type="xs:unsignedInt" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GalileoEphemerisMapItemType">
    <xs:sequence>
      <xs:element name="first" type="xs:int"/>
      <xs:element name="second" type="GalileoEphemerisType"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:complexType name="GalileoEphemerisMapType">
    <xs:sequence>
      <xs:element name="count" type="xs:nonNegativeInteger"/>
      <xs:element name="item_version" type="xs:nonNegativeInteger"/>
      <xs:element name="item" type="GalileoEphemerisMapItemType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_gal_ephemeris_map" type="GalileoEphemerisMapType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
