<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GalileoUtcType">
    <xs:sequence>
      <xs:element name="A0" type="xs:double"/>
      <xs:element name="A1" type="xs:double"/>
      <xs:element name="Delta_tLS" type="xs:int"/>
      <xs:element name="tot" type="xs:int"/>
      <xs:element name="WNot" type="xs:int"/>
      <xs:element name="WN_LSF" type="xs:int"/>
      <xs:element name="DN" type="xs:int"/>
      <xs:element name="Delta_tLSF" type="xs:int"/>
      <xs:element name="flag_utc_model" type="xs:boolean"/>
      <!-- GGTO persistence was added in Galileo_Utc_Model archive version 1. -->
      <xs:sequence minOccurs="0">
        <xs:element name="A_0G" type="xs:double"/>
        <xs:element name="A_1G" type="xs:double"/>
        <xs:element name="t_0G" type="xs:int"/>
        <xs:element name="WN_0G" type="xs:int"/>
        <xs:element name="flag_GGTO" type="xs:boolean"/>
      </xs:sequence>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_gal_utc_model" type="GalileoUtcType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
