<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GalileoIonoType">
    <xs:sequence>
      <xs:element name="ai0" type="xs:double"/>
      <xs:element name="ai1" type="xs:double"/>
      <xs:element name="ai2" type="xs:double"/>
      <xs:element name="tow" type="xs:int"/>
      <xs:element name="WN" type="xs:int"/>
      <xs:element name="Region1_flag" type="xs:boolean"/>
      <xs:element name="Region2_flag" type="xs:boolean"/>
      <xs:element name="Region3_flag" type="xs:boolean"/>
      <xs:element name="Region4_flag" type="xs:boolean"/>
      <xs:element name="Region5_flag" type="xs:boolean"/>
      <!-- Added in Galileo_Iono archive version 1. -->
      <xs:element name="valid" type="xs:boolean" minOccurs="0"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_gal_iono_model" type="GalileoIonoType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
