<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <!-- SPDX-License-Identifier: BSD-3-Clause -->
  <!-- SPDX-FileCopyrightText: 2018-2026 Carles Fernandez-Prades <carles.fernandez@cttc.es> -->
  <xs:include schemaLocation="common.xsd"/>
  <xs:complexType name="GpsAlmanacType">
    <xs:complexContent>
      <xs:extension base="GnssAlmanacType">
        <xs:sequence>
          <xs:element name="SV_health" type="xs:int"/>
          <xs:element name="AS_status" type="xs:int"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="GpsAlmanacMapItemType">
    <xs:sequence>
      <xs:element name="first" type="xs:int"/>
      <xs:element name="second" type="GpsAlmanacType"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:complexType name="GpsAlmanacMapType">
    <xs:sequence>
      <xs:element name="count" type="xs:nonNegativeInteger"/>
      <xs:element name="item_version" type="xs:nonNegativeInteger"/>
      <xs:element name="item" type="GpsAlmanacMapItemType" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attributeGroup ref="boostObjectAttributes"/>
  </xs:complexType>
  <xs:element name="boost_serialization">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="GNSS-SDR_gps_almanac_map" type="GpsAlmanacMapType"/>
      </xs:sequence>
      <xs:attributeGroup ref="boostArchiveAttributes"/>
    </xs:complexType>
  </xs:element>
</xs:schema>
