/*
 * SPDX-FileCopyrightText: (c) 2003, 2004 Lev Walkin <vlm@lionet.info>. All rights reserved.
 * SPDX-License-Identifier: BSD-1-Clause
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Components"
 *     found in "../supl-common.asn"
 */

#include "CellInfo.h"

static asn_per_constraints_t ASN_PER_TYPE_CELL_INFO_CONSTR_1 = {
    {APC_CONSTRAINED | APC_EXTENSIBLE, 2, 2, 0, 2} /* (0..2,...) */,
    {APC_UNCONSTRAINED, -1, -1, 0, 0},
    0,
    0 /* No PER value map */
};
static asn_TYPE_member_t asn_MBR_CellInfo_1[] = {
    {ATF_NOFLAGS, 0, offsetof(struct CellInfo, choice.gsmCell),
        (ASN_TAG_CLASS_CONTEXT | (0 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_GsmCellInformation,
        0, /* Defer constraints checking to the member type */
        0, /* No PER visible constraints */
        0, "gsmCell"},
    {ATF_NOFLAGS, 0, offsetof(struct CellInfo, choice.wcdmaCell),
        (ASN_TAG_CLASS_CONTEXT | (1 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_WcdmaCellInformation,
        0, /* Defer constraints checking to the member type */
        0, /* No PER visible constraints */
        0, "wcdmaCell"},
    {ATF_NOFLAGS, 0, offsetof(struct CellInfo, choice.cdmaCell),
        (ASN_TAG_CLASS_CONTEXT | (2 << 2)), -1, /* IMPLICIT tag at current level */
        &asn_DEF_CdmaCellInformation,
        0, /* Defer constraints checking to the member type */
        0, /* No PER visible constraints */
        0, "cdmaCell"},
};
static asn_TYPE_tag2member_t asn_MAP_CellInfo_tag2el_1[] = {
    {(ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0}, /* gsmCell at 61 */
    {(ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0}, /* wcdmaCell at 62 */
    {(ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0}  /* cdmaCell at 63 */
};
static asn_CHOICE_specifics_t asn_SPC_CellInfo_specs_1 = {
    sizeof(struct CellInfo),
    offsetof(struct CellInfo, _asn_ctx),
    offsetof(struct CellInfo, present),
    sizeof(((struct CellInfo *)0)->present),
    asn_MAP_CellInfo_tag2el_1,
    3, /* Count of tags in the map */
    0,
    3 /* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CellInfo = {
    "CellInfo",
    "CellInfo",
    CHOICE_free,
    CHOICE_print,
    CHOICE_constraint,
    CHOICE_decode_ber,
    CHOICE_encode_der,
    CHOICE_decode_xer,
    CHOICE_encode_xer,
    CHOICE_decode_uper,
    CHOICE_encode_uper,
    CHOICE_outmost_tag,
    0, /* No effective tags (pointer) */
    0, /* No effective tags (count) */
    0, /* No tags (pointer) */
    0, /* No tags (count) */
    &ASN_PER_TYPE_CELL_INFO_CONSTR_1,
    asn_MBR_CellInfo_1,
    3,                        /* Elements count */
    &asn_SPC_CellInfo_specs_1 /* Additional specs */
};
