/*
 * Generated by asn1c-0.9.22 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP"
 * 	found in "../supl-ulp.asn"
 */

#ifndef _DUMMY_H_
#define _DUMMY_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* DUMMY */
    typedef INTEGER_t DUMMY_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_DUMMY;
    asn_struct_free_f DUMMY_free;
    asn_struct_print_f DUMMY_print;
    asn_constr_check_f DUMMY_constraint;
    ber_type_decoder_f DUMMY_decode_ber;
    der_type_encoder_f DUMMY_encode_der;
    xer_type_decoder_f DUMMY_decode_xer;
    xer_type_encoder_f DUMMY_encode_xer;
    per_type_decoder_f DUMMY_decode_uper;
    per_type_encoder_f DUMMY_encode_uper;

#ifdef __cplusplus
}
#endif

#endif /* _DUMMY_H_ */
#include <asn_internal.h>
