/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_AcquisElement_H_
#define	_AcquisElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SatelliteID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AddionalDopplerFields;
struct AddionalAngleFields;

/* AcquisElement */
typedef struct AcquisElement {
	SatelliteID_t	 svid;
	long	 doppler0;
	struct AddionalDopplerFields	*addionalDoppler	/* OPTIONAL */;
	long	 codePhase;
	long	 intCodePhase;
	long	 gpsBitNumber;
	long	 codePhaseSearchWindow;
	struct AddionalAngleFields	*addionalAngle	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AcquisElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AcquisElement;
extern asn_SEQUENCE_specifics_t asn_SPC_AcquisElement_specs_1;
extern asn_TYPE_member_t asn_MBR_AcquisElement_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AddionalDopplerFields.h"
#include "AddionalAngleFields.h"

#endif	/* _AcquisElement_H_ */
#include <asn_internal.h>
