/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef _BadSignalElement_H_
#define _BadSignalElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SVID.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C"
{
#endif

    /* BadSignalElement */
    typedef struct BadSignalElement
    {
        SVID_t badSVID;
        long *badSignalID /* OPTIONAL */;

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } BadSignalElement_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_BadSignalElement;
    extern asn_SEQUENCE_specifics_t asn_SPC_BadSignalElement_specs_1;
    extern asn_TYPE_member_t asn_MBR_BadSignalElement_1[2];

#ifdef __cplusplus
}
#endif

#endif /* _BadSignalElement_H_ */
#include <asn_internal.h>
