/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#include "GANSS-ControlHeader.h"

asn_TYPE_member_t asn_MBR_GANSS_ControlHeader_1[] = {
	{ ATF_POINTER, 2, offsetof(struct GANSS_ControlHeader, ganssCommonAssistData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GANSSCommonAssistData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ganssCommonAssistData"
		},
	{ ATF_POINTER, 1, offsetof(struct GANSS_ControlHeader, ganssGenericAssistDataList),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SeqOfGANSSGenericAssistDataElement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ganssGenericAssistDataList"
		},
};
static const int asn_MAP_GANSS_ControlHeader_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_GANSS_ControlHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GANSS_ControlHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ganssCommonAssistData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ganssGenericAssistDataList */
};
asn_SEQUENCE_specifics_t asn_SPC_GANSS_ControlHeader_specs_1 = {
	sizeof(struct GANSS_ControlHeader),
	offsetof(struct GANSS_ControlHeader, _asn_ctx),
	asn_MAP_GANSS_ControlHeader_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_GANSS_ControlHeader_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GANSS_ControlHeader = {
	"GANSS-ControlHeader",
	"GANSS-ControlHeader",
	&asn_OP_SEQUENCE,
	asn_DEF_GANSS_ControlHeader_tags_1,
	sizeof(asn_DEF_GANSS_ControlHeader_tags_1)
		/sizeof(asn_DEF_GANSS_ControlHeader_tags_1[0]), /* 1 */
	asn_DEF_GANSS_ControlHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_GANSS_ControlHeader_tags_1)
		/sizeof(asn_DEF_GANSS_ControlHeader_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GANSS_ControlHeader_1,
	2,	/* Elements count */
	&asn_SPC_GANSS_ControlHeader_specs_1	/* Additional specs */
};

