/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_GANSS_SgnElement_H_
#define	_GANSS_SgnElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SVID.h"
#include <NativeInteger.h>
#include "MpathIndic.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GANSS-SgnElement */
typedef struct GANSS_SgnElement {
	SVID_t	 svID;
	long	 cNo;
	MpathIndic_t	 mpathDet;
	long	*carrierQualityInd	/* OPTIONAL */;
	long	 codePhase;
	long	*integerCodePhase	/* OPTIONAL */;
	long	 codePhaseRMSError;
	long	*doppler	/* OPTIONAL */;
	long	*adr	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GANSS_SgnElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GANSS_SgnElement;
extern asn_SEQUENCE_specifics_t asn_SPC_GANSS_SgnElement_specs_1;
extern asn_TYPE_member_t asn_MBR_GANSS_SgnElement_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _GANSS_SgnElement_H_ */
#include <asn_internal.h>
