/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_MultiFrameCarrier_H_
#define	_MultiFrameCarrier_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BCCHCarrier.h"
#include "MultiFrameOffset.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MultiFrameCarrier */
typedef struct MultiFrameCarrier {
	BCCHCarrier_t	 bcchCarrier;
	MultiFrameOffset_t	 multiFrameOffset;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MultiFrameCarrier_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MultiFrameCarrier;
extern asn_SEQUENCE_specifics_t asn_SPC_MultiFrameCarrier_specs_1;
extern asn_TYPE_member_t asn_MBR_MultiFrameCarrier_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _MultiFrameCarrier_H_ */
#include <asn_internal.h>
