/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_ReferenceWGS84_H_
#define	_ReferenceWGS84_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RelDistance.h"
#include "RelativeAlt.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ReferenceWGS84 */
typedef struct ReferenceWGS84 {
	RelDistance_t	 relativeNorth;
	RelDistance_t	 relativeEast;
	RelativeAlt_t	*relativeAlt	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReferenceWGS84_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReferenceWGS84;
extern asn_SEQUENCE_specifics_t asn_SPC_ReferenceWGS84_specs_1;
extern asn_TYPE_member_t asn_MBR_ReferenceWGS84_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ReferenceWGS84_H_ */
#include <asn_internal.h>
