/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_TimeSlot_H_
#define	_TimeSlot_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TimeSlot */
typedef long	 TimeSlot_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TimeSlot_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TimeSlot;
asn_struct_free_f TimeSlot_free;
asn_struct_print_f TimeSlot_print;
asn_constr_check_f TimeSlot_constraint;
ber_type_decoder_f TimeSlot_decode_ber;
der_type_encoder_f TimeSlot_encode_der;
xer_type_decoder_f TimeSlot_decode_xer;
xer_type_encoder_f TimeSlot_encode_xer;
oer_type_decoder_f TimeSlot_decode_oer;
oer_type_encoder_f TimeSlot_encode_oer;
per_type_decoder_f TimeSlot_decode_uper;
per_type_encoder_f TimeSlot_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TimeSlot_H_ */
#include <asn_internal.h>
