/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RRLP-Components"
 * 	found in "../ulp.asn1"
 */

#ifndef	_TLMReservedBits_H_
#define	_TLMReservedBits_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TLMReservedBits */
typedef long	 TLMReservedBits_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TLMReservedBits_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TLMReservedBits;
asn_struct_free_f TLMReservedBits_free;
asn_struct_print_f TLMReservedBits_print;
asn_constr_check_f TLMReservedBits_constraint;
ber_type_decoder_f TLMReservedBits_decode_ber;
der_type_encoder_f TLMReservedBits_encode_der;
xer_type_decoder_f TLMReservedBits_decode_xer;
xer_type_encoder_f TLMReservedBits_encode_xer;
oer_type_decoder_f TLMReservedBits_decode_oer;
oer_type_encoder_f TLMReservedBits_encode_oer;
per_type_decoder_f TLMReservedBits_decode_uper;
per_type_encoder_f TLMReservedBits_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TLMReservedBits_H_ */
#include <asn_internal.h>
