#!/usr/bin/env python3
"""Generate Beidou_CNAV1_ldpc.h from BDS-SIS-ICD-B1C-1.0 PDF text."""

from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICD_PDF = ROOT / "docs/article/北斗卫星导航系统-空间信号接口控制文件-公开服务信号B1C（1.0版）.pdf"
OUT = ROOT / "src/core/system_parameters/Beidou_CNAV1_ldpc.h"


def icd_text() -> str:
    proc = subprocess.run(
        ["pdftotext", "-layout", str(ICD_PDF), "-"],
        check=True,
        capture_output=True,
        text=True,
    )
    return proc.stdout


def is_numline(line: str) -> bool:
    stripped = line.strip()
    return bool(stripped) and all(part.isdigit() for part in stripped.split())


def extract_numeric_lines(
    text: str,
    start_marker: str,
    end_marker: str,
    numbers_per_line: int,
) -> list[list[int]]:
    section = text.split(start_marker, 1)[1].split(end_marker, 1)[0]
    lines = section.splitlines()
    rows: list[list[int]] = []
    for line in lines:
        if not is_numline(line):
            continue
        nums = [int(part) for part in line.split()]
        if len(nums) == numbers_per_line:
            rows.append(nums)
    return rows


def parse_matrix(
    text: str,
    start_marker: str,
    end_marker: str,
    expected_rows: int,
    row_weight: int,
) -> list[tuple[int, ...]]:
    lines = extract_numeric_lines(text, start_marker, end_marker, 16)
    if len(lines) * 16 != expected_rows * row_weight:
        raise RuntimeError(
            f"{start_marker}: expected {expected_rows * row_weight} values, got {len(lines) * 16}"
        )
    values: list[int] = []
    for line in lines:
        values.extend(line)
    rows: list[tuple[int, ...]] = []
    for row in range(expected_rows):
        base = row * row_weight
        rows.append(tuple(values[base + j] for j in range(row_weight)))
    return rows


def flatten_rows(rows: list[tuple[int, ...]]) -> list[int]:
    flat: list[int] = []
    for row in rows:
        flat.extend(row)
    return flat


def gf64_tables() -> tuple[list[int], list[int]]:
    def gf_mul(a: int, b: int) -> int:
        product = 0
        for _ in range(6):
            if b & 1:
                product ^= a
            carry = a & 0x20
            a = (a << 1) & 0x3F
            if carry:
                a ^= 0x03
            b >>= 1
        return product

    exp = [0] * 64
    log = [0] * 64
    value = 1
    for i in range(63):
        exp[i] = value
        log[value] = i
        value = gf_mul(value, 2)
    exp[63] = exp[0]
    return exp, log


def emit_array(name: str, c_type: str, values: list[int]) -> str:
    return f"constexpr {c_type} {name}[{len(values)}] = {{{','.join(map(str, values))}}};"


def main() -> None:
    text = icd_text()
    idx100 = parse_matrix(text, "H100,200,index=[", "H100,200,element=[", expected_rows=100, row_weight=4)
    el100 = parse_matrix(text, "H100,200,element=[", "H44,88,index=[", expected_rows=100, row_weight=4)
    idx44 = parse_matrix(text, "H44,88,index=[", "H44,88,element=[", expected_rows=44, row_weight=4)
    el44 = parse_matrix(text, "H44,88,element=[", "H44,88 的读取规则", expected_rows=44, row_weight=4)
    exp, log = gf64_tables()

    header: list[str] = [
        "/* Auto-generated by utils/generate_beidou_cnav1_ldpc.py. Do not edit manually. */",
        "#ifndef GNSS_SDR_BEIDOU_CNAV1_LDPC_MATRICES_H",
        "#define GNSS_SDR_BEIDOU_CNAV1_LDPC_MATRICES_H",
        "#include <cstdint>",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_N200 = 200;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_K200 = 100;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_M200 = 100;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_DC200 = 4;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_N88 = 88;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_K88 = 44;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_M88 = 44;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_DC88 = 4;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_NM = 8;",
        "constexpr int32_t BEIDOU_CNAV1_LDPC_MAX_ITER = 15;",
        "",
        "/*",
        " * GF(2^6) LUTs follow BDS-SIS-ICD-B1C-1.0 Appendix mapping tables.",
        " * Primitive polynomial: p(x)=x^6+x+1.",
        " */",
    ]
    header.append(emit_array("BEIDOU_CNAV1_H100_200_INDEX", "uint16_t", flatten_rows(idx100)))
    header.append(emit_array("BEIDOU_CNAV1_H100_200_ELEMENT", "uint8_t", flatten_rows(el100)))
    header.append(emit_array("BEIDOU_CNAV1_H44_88_INDEX", "uint16_t", flatten_rows(idx44)))
    header.append(emit_array("BEIDOU_CNAV1_H44_88_ELEMENT", "uint8_t", flatten_rows(el44)))
    header.append(emit_array("BEIDOU_CNAV1_GF64_EXP", "uint8_t", exp))
    header.append(emit_array("BEIDOU_CNAV1_GF64_LOG", "int8_t", log))
    header.append("#endif  // GNSS_SDR_BEIDOU_CNAV1_LDPC_MATRICES_H")
    OUT.write_text("\n".join(header) + "\n", encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
