; GNSS-SDR config for a 20 MHz zero-IF float32 IQ recording of BeiDou B2b
; (e.g. peiyzhou/BDS-B2b-SDR B2b_20M_out.bin). File_Signal_Source.header_size
; is in SAMPLES, not bytes: strip a 4-byte MATLAB leftover with
;   dd if=B2b_20M_out.bin of=B2b_20M_out_nohdr.bin bs=4 skip=1
; rather than setting header_size=4.
; SPDX-License-Identifier: GPL-3.0-or-later
; SPDX-FileCopyrightText: (C) 2026 Chandoss <huangchh37@mail2.sysu.edu.cn>

[GNSS-SDR]
GNSS-SDR.internal_fs_sps=20000000


SignalSource.implementation=File_Signal_Source
SignalSource.filename=./data/B2b_20M_out.bin  ; <- PUT YOUR FILE HERE
SignalSource.item_type=gr_complex
SignalSource.sampling_frequency=20000000
SignalSource.samples=0
SignalSource.repeat=false
SignalSource.dump=false
SignalSource.enable_throttle_control=false

SignalConditioner.implementation=Signal_Conditioner
DataTypeAdapter.implementation=Pass_Through
DataTypeAdapter.item_type=gr_complex
InputFilter.implementation=Pass_Through
InputFilter.item_type=gr_complex
Resampler.implementation=Pass_Through
Resampler.item_type=gr_complex
Resampler.sample_freq_in=20000000
Resampler.sample_freq_out=20000000

Channels_B2.count=12
Channels.in_acquisition=2
Channel.signal=B2

Acquisition_B2.implementation=BEIDOU_B2B_PCPS_Acquisition
Acquisition_B2.item_type=gr_complex
Acquisition_B2.coherent_integration_time_ms=1
Acquisition_B2.pfa=0.01
Acquisition_B2.doppler_max=5000
Acquisition_B2.doppler_step=500
Acquisition_B2.max_dwells=15
Acquisition_B2.dump=false
Acquisition_B2.dump_filename=./bds_b2b_acq

Tracking_B2.implementation=BEIDOU_B2B_DLL_PLL_Tracking
Tracking_B2.item_type=gr_complex
Tracking_B2.pll_bw_hz=15.0
Tracking_B2.dll_bw_hz=2.0
Tracking_B2.dump=false
Tracking_B2.dump_filename=./epl_tracking_ch_

TelemetryDecoder_B2.implementation=BEIDOU_B2B_Telemetry_Decoder
TelemetryDecoder_B2.dump=false

Observables.implementation=Hybrid_Observables
Observables.dump=false

PVT.implementation=RTKLIB_PVT
PVT.positioning_mode=Single
PVT.output_rate_ms=500
PVT.display_rate_ms=500
PVT.flag_rtklib_pvt=true
PVT.iono_model=OFF
PVT.trop_model=Saastamoinen
