/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#ifndef _ExtendedEphemeris_H_
#define _ExtendedEphemeris_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C"
{
#endif

    /* ExtendedEphemeris */
    typedef struct ExtendedEphemeris
    {
        long validity;
        /*
	 * This type is extensible,
	 * possible extensions are below.
	 */

        /* Context for parsing across buffer boundaries */
        asn_struct_ctx_t _asn_ctx;
    } ExtendedEphemeris_t;

    /* Implementation */
    extern asn_TYPE_descriptor_t asn_DEF_ExtendedEphemeris;
    extern asn_SEQUENCE_specifics_t asn_SPC_ExtendedEphemeris_specs_1;
    extern asn_TYPE_member_t asn_MBR_ExtendedEphemeris_1[1];

#ifdef __cplusplus
}
#endif

#endif /* _ExtendedEphemeris_H_ */
#include "asn_internal.h"
