/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#include "MeasResultEUTRA.h"

static asn_TYPE_member_t asn_MBR_cgi_Info_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, cellGlobalId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellGlobalIdEUTRA,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cellGlobalId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA__cgi_Info, trackingAreaCode),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrackingAreaCode,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trackingAreaCode"
		},
};
static const ber_tlv_tag_t asn_DEF_cgi_Info_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_cgi_Info_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cellGlobalId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* trackingAreaCode */
};
static asn_SEQUENCE_specifics_t asn_SPC_cgi_Info_specs_3 = {
	sizeof(struct MeasResultEUTRA__cgi_Info),
	offsetof(struct MeasResultEUTRA__cgi_Info, _asn_ctx),
	asn_MAP_cgi_Info_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cgi_Info_3 = {
	"cgi-Info",
	"cgi-Info",
	&asn_OP_SEQUENCE,
	asn_DEF_cgi_Info_tags_3,
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]) - 1, /* 1 */
	asn_DEF_cgi_Info_tags_3,	/* Same as above */
	sizeof(asn_DEF_cgi_Info_tags_3)
		/sizeof(asn_DEF_cgi_Info_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_cgi_Info_3,
	2,	/* Elements count */
	&asn_SPC_cgi_Info_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_measResult_6[] = {
	{ ATF_POINTER, 2, offsetof(struct MeasResultEUTRA__measResult, rsrpResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRP_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrpResult"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA__measResult, rsrqResult),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RSRQ_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsrqResult"
		},
};
static const int asn_MAP_measResult_oms_6[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_measResult_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_measResult_tag2el_6[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rsrpResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* rsrqResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_measResult_specs_6 = {
	sizeof(struct MeasResultEUTRA__measResult),
	offsetof(struct MeasResultEUTRA__measResult, _asn_ctx),
	asn_MAP_measResult_tag2el_6,
	2,	/* Count of tags in the map */
	asn_MAP_measResult_oms_6,	/* Optional members */
	2, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_measResult_6 = {
	"measResult",
	"measResult",
	&asn_OP_SEQUENCE,
	asn_DEF_measResult_tags_6,
	sizeof(asn_DEF_measResult_tags_6)
		/sizeof(asn_DEF_measResult_tags_6[0]) - 1, /* 1 */
	asn_DEF_measResult_tags_6,	/* Same as above */
	sizeof(asn_DEF_measResult_tags_6)
		/sizeof(asn_DEF_measResult_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_measResult_6,
	2,	/* Elements count */
	&asn_SPC_measResult_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_MeasResultEUTRA_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, physCellId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PhysCellId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"physCellId"
		},
	{ ATF_POINTER, 1, offsetof(struct MeasResultEUTRA, cgi_Info),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_cgi_Info_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cgi-Info"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasResultEUTRA, measResult),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_measResult_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"measResult"
		},
};
static const int asn_MAP_MeasResultEUTRA_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_MeasResultEUTRA_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MeasResultEUTRA_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* physCellId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cgi-Info */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* measResult */
};
asn_SEQUENCE_specifics_t asn_SPC_MeasResultEUTRA_specs_1 = {
	sizeof(struct MeasResultEUTRA),
	offsetof(struct MeasResultEUTRA, _asn_ctx),
	asn_MAP_MeasResultEUTRA_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_MeasResultEUTRA_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MeasResultEUTRA = {
	"MeasResultEUTRA",
	"MeasResultEUTRA",
	&asn_OP_SEQUENCE,
	asn_DEF_MeasResultEUTRA_tags_1,
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	asn_DEF_MeasResultEUTRA_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasResultEUTRA_tags_1)
		/sizeof(asn_DEF_MeasResultEUTRA_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MeasResultEUTRA_1,
	3,	/* Elements count */
	&asn_SPC_MeasResultEUTRA_specs_1	/* Additional specs */
};

