/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-START"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#include "PosTechnology.h"

asn_TYPE_member_t asn_MBR_PosTechnology_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, agpsSETassisted),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"agpsSETassisted"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, agpsSETBased),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"agpsSETBased"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, autonomousGPS),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"autonomousGPS"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, aFLT),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aFLT"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, eCID),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eCID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, eOTD),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eOTD"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PosTechnology, oTDOA),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"oTDOA"
		},
	{ ATF_POINTER, 1, offsetof(struct PosTechnology, ver2_PosTechnology_extension),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Ver2_PosTechnology_extension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ver2-PosTechnology-extension"
		},
};
static const int asn_MAP_PosTechnology_oms_1[] = { 7 };
static const ber_tlv_tag_t asn_DEF_PosTechnology_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PosTechnology_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* agpsSETassisted */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* agpsSETBased */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* autonomousGPS */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* aFLT */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* eCID */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* eOTD */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* oTDOA */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* ver2-PosTechnology-extension */
};
asn_SEQUENCE_specifics_t asn_SPC_PosTechnology_specs_1 = {
	sizeof(struct PosTechnology),
	offsetof(struct PosTechnology, _asn_ctx),
	asn_MAP_PosTechnology_tag2el_1,
	8,	/* Count of tags in the map */
	asn_MAP_PosTechnology_oms_1,	/* Optional members */
	0, 1,	/* Root/Additions */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PosTechnology = {
	"PosTechnology",
	"PosTechnology",
	&asn_OP_SEQUENCE,
	asn_DEF_PosTechnology_tags_1,
	sizeof(asn_DEF_PosTechnology_tags_1)
		/sizeof(asn_DEF_PosTechnology_tags_1[0]), /* 1 */
	asn_DEF_PosTechnology_tags_1,	/* Same as above */
	sizeof(asn_DEF_PosTechnology_tags_1)
		/sizeof(asn_DEF_PosTechnology_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PosTechnology_1,
	8,	/* Elements count */
	&asn_SPC_PosTechnology_specs_1	/* Additional specs */
};

