/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Components"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#include "StatusCode.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_StatusCode_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  19 }	/* (0..19,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_StatusCode_value2enum_1[] = {
	{ 0,	11,	"unspecified" },
	{ 1,	13,	"systemFailure" },
	{ 2,	17,	"unexpectedMessage" },
	{ 3,	13,	"protocolError" },
	{ 4,	11,	"dataMissing" },
	{ 5,	19,	"unexpectedDataValue" },
	{ 6,	16,	"posMethodFailure" },
	{ 7,	17,	"posMethodMismatch" },
	{ 8,	19,	"posProtocolMismatch" },
	{ 9,	21,	"targetSETnotReachable" },
	{ 10,	19,	"versionNotSupported" },
	{ 11,	16,	"resourceShortage" },
	{ 12,	16,	"invalidSessionId" },
	{ 13,	24,	"nonProxyModeNotSupported" },
	{ 14,	21,	"proxyModeNotSupported" },
	{ 15,	23,	"positioningNotPermitted" },
	{ 16,	14,	"authNetFailure" },
	{ 17,	19,	"authSuplinitFailure" },
	{ 18,	32,	"ver2-incompatibleProtectionLevel" },
	{ 19,	24,	"ver2-serviceNotSupported" },
	{ 20,	25,	"ver2-insufficientInterval" },
	{ 21,	19,	"ver2-noSUPLCoverage" },
	{ 100,	19,	"consentDeniedByUser" },
	{ 101,	20,	"consentGrantedByUser" },
	{ 102,	19,	"ver2-sessionStopped" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_StatusCode_enum2value_1[] = {
	16,	/* authNetFailure(16) */
	17,	/* authSuplinitFailure(17) */
	22,	/* consentDeniedByUser(100) */
	23,	/* consentGrantedByUser(101) */
	4,	/* dataMissing(4) */
	12,	/* invalidSessionId(12) */
	13,	/* nonProxyModeNotSupported(13) */
	6,	/* posMethodFailure(6) */
	7,	/* posMethodMismatch(7) */
	8,	/* posProtocolMismatch(8) */
	15,	/* positioningNotPermitted(15) */
	3,	/* protocolError(3) */
	14,	/* proxyModeNotSupported(14) */
	11,	/* resourceShortage(11) */
	1,	/* systemFailure(1) */
	9,	/* targetSETnotReachable(9) */
	5,	/* unexpectedDataValue(5) */
	2,	/* unexpectedMessage(2) */
	0,	/* unspecified(0) */
	18,	/* ver2-incompatibleProtectionLevel(18) */
	20,	/* ver2-insufficientInterval(20) */
	21,	/* ver2-noSUPLCoverage(21) */
	19,	/* ver2-serviceNotSupported(19) */
	24,	/* ver2-sessionStopped(102) */
	10	/* versionNotSupported(10) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_StatusCode_specs_1 = {
	asn_MAP_StatusCode_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_StatusCode_enum2value_1,	/* N => "tag"; sorted by N */
	25,	/* Number of elements in the maps */
	21,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_StatusCode_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_StatusCode = {
	"StatusCode",
	"StatusCode",
	&asn_OP_NativeEnumerated,
	asn_DEF_StatusCode_tags_1,
	sizeof(asn_DEF_StatusCode_tags_1)
		/sizeof(asn_DEF_StatusCode_tags_1[0]), /* 1 */
	asn_DEF_StatusCode_tags_1,	/* Same as above */
	sizeof(asn_DEF_StatusCode_tags_1)
		/sizeof(asn_DEF_StatusCode_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_StatusCode_constr_1, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_StatusCode_specs_1	/* Additional specs */
};

