/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#ifndef	_SupportedBearers_H_
#define	_SupportedBearers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SupportedBearers */
typedef struct SupportedBearers {
	BOOLEAN_t	 gsm;
	BOOLEAN_t	 wcdma;
	BOOLEAN_t	 lte;
	BOOLEAN_t	 cdma;
	BOOLEAN_t	 hprd;
	BOOLEAN_t	 umb;
	BOOLEAN_t	 wlan;
	BOOLEAN_t	 wiMAX;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedBearers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedBearers;
extern asn_SEQUENCE_specifics_t asn_SPC_SupportedBearers_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedBearers_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedBearers_H_ */
#include "asn_internal.h"
