/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ULP-Version-2-parameter-extensions"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#include "Supported3GPP2PosProtocolVersion.h"

static int
memb_revisionNumber_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const BIT_STRING_t *st = (const BIT_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if(st->size > 0) {
		/* Size in bits */
		size = 8 * st->size - (st->bits_unused & 0x07);
	} else {
		size = 0;
	}
	
	if((size == 6)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_pointReleaseNumber_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_internalEditLevel_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_revisionNumber_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 0,  0,  6,  6 }	/* (SIZE(6..6)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_pointReleaseNumber_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_internalEditLevel_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_Supported3GPP2PosProtocolVersion_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Supported3GPP2PosProtocolVersion, revisionNumber),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, &asn_PER_memb_revisionNumber_constr_2,  memb_revisionNumber_constraint_1 },
		0, 0, /* No default value */
		"revisionNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Supported3GPP2PosProtocolVersion, pointReleaseNumber),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_pointReleaseNumber_constr_3,  memb_pointReleaseNumber_constraint_1 },
		0, 0, /* No default value */
		"pointReleaseNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Supported3GPP2PosProtocolVersion, internalEditLevel),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_internalEditLevel_constr_4,  memb_internalEditLevel_constraint_1 },
		0, 0, /* No default value */
		"internalEditLevel"
		},
};
static const ber_tlv_tag_t asn_DEF_Supported3GPP2PosProtocolVersion_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Supported3GPP2PosProtocolVersion_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* revisionNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* pointReleaseNumber */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* internalEditLevel */
};
asn_SEQUENCE_specifics_t asn_SPC_Supported3GPP2PosProtocolVersion_specs_1 = {
	sizeof(struct Supported3GPP2PosProtocolVersion),
	offsetof(struct Supported3GPP2PosProtocolVersion, _asn_ctx),
	asn_MAP_Supported3GPP2PosProtocolVersion_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Supported3GPP2PosProtocolVersion = {
	"Supported3GPP2PosProtocolVersion",
	"Supported3GPP2PosProtocolVersion",
	&asn_OP_SEQUENCE,
	asn_DEF_Supported3GPP2PosProtocolVersion_tags_1,
	sizeof(asn_DEF_Supported3GPP2PosProtocolVersion_tags_1)
		/sizeof(asn_DEF_Supported3GPP2PosProtocolVersion_tags_1[0]), /* 1 */
	asn_DEF_Supported3GPP2PosProtocolVersion_tags_1,	/* Same as above */
	sizeof(asn_DEF_Supported3GPP2PosProtocolVersion_tags_1)
		/sizeof(asn_DEF_Supported3GPP2PosProtocolVersion_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Supported3GPP2PosProtocolVersion_1,
	3,	/* Elements count */
	&asn_SPC_Supported3GPP2PosProtocolVersion_specs_1	/* Additional specs */
};

