/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ver2-ULP-Components"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#include "Ver2-ULP-Components_RepMode.h"

asn_TYPE_member_t asn_MBR_Ver2_ULP_Components_RepMode_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Ver2_ULP_Components_RepMode, realtime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"realtime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ver2_ULP_Components_RepMode, quasirealtime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"quasirealtime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Ver2_ULP_Components_RepMode, batch),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"batch"
		},
};
static const ber_tlv_tag_t asn_DEF_Ver2_ULP_Components_RepMode_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Ver2_ULP_Components_RepMode_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* realtime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* quasirealtime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* batch */
};
asn_SEQUENCE_specifics_t asn_SPC_Ver2_ULP_Components_RepMode_specs_1 = {
	sizeof(struct Ver2_ULP_Components_RepMode),
	offsetof(struct Ver2_ULP_Components_RepMode, _asn_ctx),
	asn_MAP_Ver2_ULP_Components_RepMode_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Ver2_ULP_Components_RepMode = {
	"RepMode",
	"RepMode",
	&asn_OP_SEQUENCE,
	asn_DEF_Ver2_ULP_Components_RepMode_tags_1,
	sizeof(asn_DEF_Ver2_ULP_Components_RepMode_tags_1)
		/sizeof(asn_DEF_Ver2_ULP_Components_RepMode_tags_1[0]), /* 1 */
	asn_DEF_Ver2_ULP_Components_RepMode_tags_1,	/* Same as above */
	sizeof(asn_DEF_Ver2_ULP_Components_RepMode_tags_1)
		/sizeof(asn_DEF_Ver2_ULP_Components_RepMode_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Ver2_ULP_Components_RepMode_1,
	3,	/* Elements count */
	&asn_SPC_Ver2_ULP_Components_RepMode_specs_1	/* Additional specs */
};

