/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SUPL-TRIGGERED-START"
 * 	found in "../ulp.asn1"
 * 	`asn1c -S ../../skeletons -pdu=ULP-PDU -pdu=SUPLINIT -fcompound-names -no-gen-OER`
 */

#ifndef	_WCDMAAreaId_H_
#define	_WCDMAAreaId_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* WCDMAAreaId */
typedef struct WCDMAAreaId {
	long	*refMCC	/* OPTIONAL */;
	long	*refMNC	/* OPTIONAL */;
	long	*refLAC	/* OPTIONAL */;
	long	*refUC	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} WCDMAAreaId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_WCDMAAreaId;
extern asn_SEQUENCE_specifics_t asn_SPC_WCDMAAreaId_specs_1;
extern asn_TYPE_member_t asn_MBR_WCDMAAreaId_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _WCDMAAreaId_H_ */
#include "asn_internal.h"
